// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lkv.proto

#include "lkv.pb.h"
#include "lkv.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace lkvrpc {

static const char* LKV_method_names[] = {
  "/lkvrpc.LKV/Get",
  "/lkvrpc.LKV/Put",
  "/lkvrpc.LKV/Delete",
};

std::unique_ptr< LKV::Stub> LKV::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< LKV::Stub> stub(new LKV::Stub(channel));
  return stub;
}

LKV::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Get_(LKV_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Put_(LKV_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(LKV_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LKV::Stub::Get(::grpc::ClientContext* context, const ::lkvrpc::Key& request, ::lkvrpc::Value* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::lkvrpc::Value>* LKV::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::lkvrpc::Key& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::lkvrpc::Value>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::Status LKV::Stub::Put(::grpc::ClientContext* context, const ::lkvrpc::KeyValuePair& request, ::lkvrpc::ReturnInt* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::lkvrpc::ReturnInt>* LKV::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::lkvrpc::KeyValuePair& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::lkvrpc::ReturnInt>(channel_.get(), cq, rpcmethod_Put_, context, request);
}

::grpc::Status LKV::Stub::Delete(::grpc::ClientContext* context, const ::lkvrpc::Key& request, ::lkvrpc::ReturnInt* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_Delete_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::lkvrpc::ReturnInt>* LKV::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::lkvrpc::Key& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::lkvrpc::ReturnInt>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

LKV::Service::Service() {
  AddMethod(new ::grpc::RpcServiceMethod(
      LKV_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< LKV::Service, ::lkvrpc::Key, ::lkvrpc::Value>(
          std::mem_fn(&LKV::Service::Get), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      LKV_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< LKV::Service, ::lkvrpc::KeyValuePair, ::lkvrpc::ReturnInt>(
          std::mem_fn(&LKV::Service::Put), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      LKV_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< LKV::Service, ::lkvrpc::Key, ::lkvrpc::ReturnInt>(
          std::mem_fn(&LKV::Service::Delete), this)));
}

LKV::Service::~Service() {
}

::grpc::Status LKV::Service::Get(::grpc::ServerContext* context, const ::lkvrpc::Key* request, ::lkvrpc::Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LKV::Service::Put(::grpc::ServerContext* context, const ::lkvrpc::KeyValuePair* request, ::lkvrpc::ReturnInt* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LKV::Service::Delete(::grpc::ServerContext* context, const ::lkvrpc::Key* request, ::lkvrpc::ReturnInt* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace lkvrpc

