// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_paxos.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "simple_paxos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace simplepaxos {

namespace {

const ::google::protobuf::Descriptor* PrepareRet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PrepareRet_reflection_ = NULL;
const ::google::protobuf::Descriptor* AcceptRet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AcceptRet_reflection_ = NULL;
const ::google::protobuf::Descriptor* Prepare_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Prepare_reflection_ = NULL;
const ::google::protobuf::Descriptor* Accept_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Accept_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_simple_5fpaxos_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_simple_5fpaxos_2eproto() {
  protobuf_AddDesc_simple_5fpaxos_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "simple_paxos.proto");
  GOOGLE_CHECK(file != NULL);
  PrepareRet_descriptor_ = file->message_type(0);
  static const int PrepareRet_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, proposaln_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, acceptern_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, accepterv_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, isok_),
  };
  PrepareRet_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PrepareRet_descriptor_,
      PrepareRet::default_instance_,
      PrepareRet_offsets_,
      -1,
      -1,
      -1,
      sizeof(PrepareRet),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrepareRet, _is_default_instance_));
  AcceptRet_descriptor_ = file->message_type(1);
  static const int AcceptRet_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptRet, proposaln_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptRet, isok_),
  };
  AcceptRet_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AcceptRet_descriptor_,
      AcceptRet::default_instance_,
      AcceptRet_offsets_,
      -1,
      -1,
      -1,
      sizeof(AcceptRet),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptRet, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AcceptRet, _is_default_instance_));
  Prepare_descriptor_ = file->message_type(2);
  static const int Prepare_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Prepare, proposaln_),
  };
  Prepare_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Prepare_descriptor_,
      Prepare::default_instance_,
      Prepare_offsets_,
      -1,
      -1,
      -1,
      sizeof(Prepare),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Prepare, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Prepare, _is_default_instance_));
  Accept_descriptor_ = file->message_type(3);
  static const int Accept_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accept, acceptern_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accept, accepterv_),
  };
  Accept_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Accept_descriptor_,
      Accept::default_instance_,
      Accept_offsets_,
      -1,
      -1,
      -1,
      sizeof(Accept),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accept, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Accept, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_simple_5fpaxos_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PrepareRet_descriptor_, &PrepareRet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AcceptRet_descriptor_, &AcceptRet::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Prepare_descriptor_, &Prepare::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Accept_descriptor_, &Accept::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_simple_5fpaxos_2eproto() {
  delete PrepareRet::default_instance_;
  delete PrepareRet_reflection_;
  delete AcceptRet::default_instance_;
  delete AcceptRet_reflection_;
  delete Prepare::default_instance_;
  delete Prepare_reflection_;
  delete Accept::default_instance_;
  delete Accept_reflection_;
}

void protobuf_AddDesc_simple_5fpaxos_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_simple_5fpaxos_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022simple_paxos.proto\022\013simplepaxos\"S\n\nPre"
    "pareRet\022\021\n\tproposaln\030\001 \001(\004\022\021\n\tacceptern\030"
    "\002 \001(\004\022\021\n\taccepterv\030\003 \001(\t\022\014\n\004isok\030\004 \001(\010\","
    "\n\tAcceptRet\022\021\n\tproposaln\030\001 \001(\004\022\014\n\004isok\030\002"
    " \001(\010\"\034\n\007Prepare\022\021\n\tproposaln\030\001 \001(\004\".\n\006Ac"
    "cept\022\021\n\tacceptern\030\001 \001(\004\022\021\n\taccepterv\030\002 \001"
    "(\t2\216\001\n\013SimplePaxos\022=\n\014HandleAccept\022\023.sim"
    "plepaxos.Accept\032\026.simplepaxos.AcceptRet\""
    "\000\022@\n\rHandlePrepare\022\024.simplepaxos.Prepare"
    "\032\027.simplepaxos.PrepareRet\"\000b\006proto3", 395);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "simple_paxos.proto", &protobuf_RegisterTypes);
  PrepareRet::default_instance_ = new PrepareRet();
  AcceptRet::default_instance_ = new AcceptRet();
  Prepare::default_instance_ = new Prepare();
  Accept::default_instance_ = new Accept();
  PrepareRet::default_instance_->InitAsDefaultInstance();
  AcceptRet::default_instance_->InitAsDefaultInstance();
  Prepare::default_instance_->InitAsDefaultInstance();
  Accept::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_simple_5fpaxos_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_simple_5fpaxos_2eproto {
  StaticDescriptorInitializer_simple_5fpaxos_2eproto() {
    protobuf_AddDesc_simple_5fpaxos_2eproto();
  }
} static_descriptor_initializer_simple_5fpaxos_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PrepareRet::kProposalnFieldNumber;
const int PrepareRet::kAccepternFieldNumber;
const int PrepareRet::kAcceptervFieldNumber;
const int PrepareRet::kIsokFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PrepareRet::PrepareRet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:simplepaxos.PrepareRet)
}

void PrepareRet::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PrepareRet::PrepareRet(const PrepareRet& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:simplepaxos.PrepareRet)
}

void PrepareRet::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  proposaln_ = GOOGLE_ULONGLONG(0);
  acceptern_ = GOOGLE_ULONGLONG(0);
  accepterv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isok_ = false;
}

PrepareRet::~PrepareRet() {
  // @@protoc_insertion_point(destructor:simplepaxos.PrepareRet)
  SharedDtor();
}

void PrepareRet::SharedDtor() {
  accepterv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PrepareRet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PrepareRet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PrepareRet_descriptor_;
}

const PrepareRet& PrepareRet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_simple_5fpaxos_2eproto();
  return *default_instance_;
}

PrepareRet* PrepareRet::default_instance_ = NULL;

PrepareRet* PrepareRet::New(::google::protobuf::Arena* arena) const {
  PrepareRet* n = new PrepareRet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PrepareRet::Clear() {
// @@protoc_insertion_point(message_clear_start:simplepaxos.PrepareRet)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PrepareRet, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PrepareRet*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(proposaln_, acceptern_);
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isok_ = false;

#undef ZR_HELPER_
#undef ZR_

}

bool PrepareRet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:simplepaxos.PrepareRet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 proposaln = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &proposaln_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_acceptern;
        break;
      }

      // optional uint64 acceptern = 2;
      case 2: {
        if (tag == 16) {
         parse_acceptern:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &acceptern_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_accepterv;
        break;
      }

      // optional string accepterv = 3;
      case 3: {
        if (tag == 26) {
         parse_accepterv:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accepterv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->accepterv().data(), this->accepterv().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "simplepaxos.PrepareRet.accepterv"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_isok;
        break;
      }

      // optional bool isok = 4;
      case 4: {
        if (tag == 32) {
         parse_isok:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isok_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:simplepaxos.PrepareRet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:simplepaxos.PrepareRet)
  return false;
#undef DO_
}

void PrepareRet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:simplepaxos.PrepareRet)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->proposaln(), output);
  }

  // optional uint64 acceptern = 2;
  if (this->acceptern() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->acceptern(), output);
  }

  // optional string accepterv = 3;
  if (this->accepterv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accepterv().data(), this->accepterv().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "simplepaxos.PrepareRet.accepterv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->accepterv(), output);
  }

  // optional bool isok = 4;
  if (this->isok() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->isok(), output);
  }

  // @@protoc_insertion_point(serialize_end:simplepaxos.PrepareRet)
}

::google::protobuf::uint8* PrepareRet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:simplepaxos.PrepareRet)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->proposaln(), target);
  }

  // optional uint64 acceptern = 2;
  if (this->acceptern() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->acceptern(), target);
  }

  // optional string accepterv = 3;
  if (this->accepterv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accepterv().data(), this->accepterv().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "simplepaxos.PrepareRet.accepterv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->accepterv(), target);
  }

  // optional bool isok = 4;
  if (this->isok() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->isok(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:simplepaxos.PrepareRet)
  return target;
}

int PrepareRet::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:simplepaxos.PrepareRet)
  int total_size = 0;

  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->proposaln());
  }

  // optional uint64 acceptern = 2;
  if (this->acceptern() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->acceptern());
  }

  // optional string accepterv = 3;
  if (this->accepterv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->accepterv());
  }

  // optional bool isok = 4;
  if (this->isok() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PrepareRet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:simplepaxos.PrepareRet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PrepareRet* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PrepareRet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:simplepaxos.PrepareRet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:simplepaxos.PrepareRet)
    MergeFrom(*source);
  }
}

void PrepareRet::MergeFrom(const PrepareRet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:simplepaxos.PrepareRet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.proposaln() != 0) {
    set_proposaln(from.proposaln());
  }
  if (from.acceptern() != 0) {
    set_acceptern(from.acceptern());
  }
  if (from.accepterv().size() > 0) {

    accepterv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accepterv_);
  }
  if (from.isok() != 0) {
    set_isok(from.isok());
  }
}

void PrepareRet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:simplepaxos.PrepareRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrepareRet::CopyFrom(const PrepareRet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:simplepaxos.PrepareRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrepareRet::IsInitialized() const {

  return true;
}

void PrepareRet::Swap(PrepareRet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PrepareRet::InternalSwap(PrepareRet* other) {
  std::swap(proposaln_, other->proposaln_);
  std::swap(acceptern_, other->acceptern_);
  accepterv_.Swap(&other->accepterv_);
  std::swap(isok_, other->isok_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PrepareRet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PrepareRet_descriptor_;
  metadata.reflection = PrepareRet_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PrepareRet

// optional uint64 proposaln = 1;
void PrepareRet::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 PrepareRet::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.proposaln)
  return proposaln_;
}
 void PrepareRet::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.proposaln)
}

// optional uint64 acceptern = 2;
void PrepareRet::clear_acceptern() {
  acceptern_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 PrepareRet::acceptern() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.acceptern)
  return acceptern_;
}
 void PrepareRet::set_acceptern(::google::protobuf::uint64 value) {
  
  acceptern_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.acceptern)
}

// optional string accepterv = 3;
void PrepareRet::clear_accepterv() {
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PrepareRet::accepterv() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.accepterv)
  return accepterv_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PrepareRet::set_accepterv(const ::std::string& value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.accepterv)
}
 void PrepareRet::set_accepterv(const char* value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:simplepaxos.PrepareRet.accepterv)
}
 void PrepareRet::set_accepterv(const char* value, size_t size) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:simplepaxos.PrepareRet.accepterv)
}
 ::std::string* PrepareRet::mutable_accepterv() {
  
  // @@protoc_insertion_point(field_mutable:simplepaxos.PrepareRet.accepterv)
  return accepterv_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PrepareRet::release_accepterv() {
  // @@protoc_insertion_point(field_release:simplepaxos.PrepareRet.accepterv)
  
  return accepterv_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PrepareRet::set_allocated_accepterv(::std::string* accepterv) {
  if (accepterv != NULL) {
    
  } else {
    
  }
  accepterv_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accepterv);
  // @@protoc_insertion_point(field_set_allocated:simplepaxos.PrepareRet.accepterv)
}

// optional bool isok = 4;
void PrepareRet::clear_isok() {
  isok_ = false;
}
 bool PrepareRet::isok() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.isok)
  return isok_;
}
 void PrepareRet::set_isok(bool value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.isok)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AcceptRet::kProposalnFieldNumber;
const int AcceptRet::kIsokFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AcceptRet::AcceptRet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:simplepaxos.AcceptRet)
}

void AcceptRet::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AcceptRet::AcceptRet(const AcceptRet& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:simplepaxos.AcceptRet)
}

void AcceptRet::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  proposaln_ = GOOGLE_ULONGLONG(0);
  isok_ = false;
}

AcceptRet::~AcceptRet() {
  // @@protoc_insertion_point(destructor:simplepaxos.AcceptRet)
  SharedDtor();
}

void AcceptRet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AcceptRet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AcceptRet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AcceptRet_descriptor_;
}

const AcceptRet& AcceptRet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_simple_5fpaxos_2eproto();
  return *default_instance_;
}

AcceptRet* AcceptRet::default_instance_ = NULL;

AcceptRet* AcceptRet::New(::google::protobuf::Arena* arena) const {
  AcceptRet* n = new AcceptRet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AcceptRet::Clear() {
// @@protoc_insertion_point(message_clear_start:simplepaxos.AcceptRet)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(AcceptRet, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<AcceptRet*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(proposaln_, isok_);

#undef ZR_HELPER_
#undef ZR_

}

bool AcceptRet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:simplepaxos.AcceptRet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 proposaln = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &proposaln_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_isok;
        break;
      }

      // optional bool isok = 2;
      case 2: {
        if (tag == 16) {
         parse_isok:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isok_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:simplepaxos.AcceptRet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:simplepaxos.AcceptRet)
  return false;
#undef DO_
}

void AcceptRet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:simplepaxos.AcceptRet)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->proposaln(), output);
  }

  // optional bool isok = 2;
  if (this->isok() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->isok(), output);
  }

  // @@protoc_insertion_point(serialize_end:simplepaxos.AcceptRet)
}

::google::protobuf::uint8* AcceptRet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:simplepaxos.AcceptRet)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->proposaln(), target);
  }

  // optional bool isok = 2;
  if (this->isok() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->isok(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:simplepaxos.AcceptRet)
  return target;
}

int AcceptRet::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:simplepaxos.AcceptRet)
  int total_size = 0;

  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->proposaln());
  }

  // optional bool isok = 2;
  if (this->isok() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AcceptRet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:simplepaxos.AcceptRet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const AcceptRet* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const AcceptRet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:simplepaxos.AcceptRet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:simplepaxos.AcceptRet)
    MergeFrom(*source);
  }
}

void AcceptRet::MergeFrom(const AcceptRet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:simplepaxos.AcceptRet)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.proposaln() != 0) {
    set_proposaln(from.proposaln());
  }
  if (from.isok() != 0) {
    set_isok(from.isok());
  }
}

void AcceptRet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:simplepaxos.AcceptRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AcceptRet::CopyFrom(const AcceptRet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:simplepaxos.AcceptRet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AcceptRet::IsInitialized() const {

  return true;
}

void AcceptRet::Swap(AcceptRet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AcceptRet::InternalSwap(AcceptRet* other) {
  std::swap(proposaln_, other->proposaln_);
  std::swap(isok_, other->isok_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AcceptRet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AcceptRet_descriptor_;
  metadata.reflection = AcceptRet_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AcceptRet

// optional uint64 proposaln = 1;
void AcceptRet::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 AcceptRet::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.AcceptRet.proposaln)
  return proposaln_;
}
 void AcceptRet::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.AcceptRet.proposaln)
}

// optional bool isok = 2;
void AcceptRet::clear_isok() {
  isok_ = false;
}
 bool AcceptRet::isok() const {
  // @@protoc_insertion_point(field_get:simplepaxos.AcceptRet.isok)
  return isok_;
}
 void AcceptRet::set_isok(bool value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.AcceptRet.isok)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Prepare::kProposalnFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Prepare::Prepare()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:simplepaxos.Prepare)
}

void Prepare::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Prepare::Prepare(const Prepare& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:simplepaxos.Prepare)
}

void Prepare::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  proposaln_ = GOOGLE_ULONGLONG(0);
}

Prepare::~Prepare() {
  // @@protoc_insertion_point(destructor:simplepaxos.Prepare)
  SharedDtor();
}

void Prepare::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Prepare::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Prepare::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Prepare_descriptor_;
}

const Prepare& Prepare::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_simple_5fpaxos_2eproto();
  return *default_instance_;
}

Prepare* Prepare::default_instance_ = NULL;

Prepare* Prepare::New(::google::protobuf::Arena* arena) const {
  Prepare* n = new Prepare;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Prepare::Clear() {
// @@protoc_insertion_point(message_clear_start:simplepaxos.Prepare)
  proposaln_ = GOOGLE_ULONGLONG(0);
}

bool Prepare::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:simplepaxos.Prepare)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 proposaln = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &proposaln_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:simplepaxos.Prepare)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:simplepaxos.Prepare)
  return false;
#undef DO_
}

void Prepare::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:simplepaxos.Prepare)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->proposaln(), output);
  }

  // @@protoc_insertion_point(serialize_end:simplepaxos.Prepare)
}

::google::protobuf::uint8* Prepare::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:simplepaxos.Prepare)
  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->proposaln(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:simplepaxos.Prepare)
  return target;
}

int Prepare::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:simplepaxos.Prepare)
  int total_size = 0;

  // optional uint64 proposaln = 1;
  if (this->proposaln() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->proposaln());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Prepare::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:simplepaxos.Prepare)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Prepare* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Prepare>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:simplepaxos.Prepare)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:simplepaxos.Prepare)
    MergeFrom(*source);
  }
}

void Prepare::MergeFrom(const Prepare& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:simplepaxos.Prepare)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.proposaln() != 0) {
    set_proposaln(from.proposaln());
  }
}

void Prepare::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:simplepaxos.Prepare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Prepare::CopyFrom(const Prepare& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:simplepaxos.Prepare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Prepare::IsInitialized() const {

  return true;
}

void Prepare::Swap(Prepare* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Prepare::InternalSwap(Prepare* other) {
  std::swap(proposaln_, other->proposaln_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Prepare::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Prepare_descriptor_;
  metadata.reflection = Prepare_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Prepare

// optional uint64 proposaln = 1;
void Prepare::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 Prepare::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Prepare.proposaln)
  return proposaln_;
}
 void Prepare::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Prepare.proposaln)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Accept::kAccepternFieldNumber;
const int Accept::kAcceptervFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Accept::Accept()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:simplepaxos.Accept)
}

void Accept::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Accept::Accept(const Accept& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:simplepaxos.Accept)
}

void Accept::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  acceptern_ = GOOGLE_ULONGLONG(0);
  accepterv_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Accept::~Accept() {
  // @@protoc_insertion_point(destructor:simplepaxos.Accept)
  SharedDtor();
}

void Accept::SharedDtor() {
  accepterv_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Accept::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Accept::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Accept_descriptor_;
}

const Accept& Accept::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_simple_5fpaxos_2eproto();
  return *default_instance_;
}

Accept* Accept::default_instance_ = NULL;

Accept* Accept::New(::google::protobuf::Arena* arena) const {
  Accept* n = new Accept;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Accept::Clear() {
// @@protoc_insertion_point(message_clear_start:simplepaxos.Accept)
  acceptern_ = GOOGLE_ULONGLONG(0);
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Accept::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:simplepaxos.Accept)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 acceptern = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &acceptern_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_accepterv;
        break;
      }

      // optional string accepterv = 2;
      case 2: {
        if (tag == 18) {
         parse_accepterv:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accepterv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->accepterv().data(), this->accepterv().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "simplepaxos.Accept.accepterv"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:simplepaxos.Accept)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:simplepaxos.Accept)
  return false;
#undef DO_
}

void Accept::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:simplepaxos.Accept)
  // optional uint64 acceptern = 1;
  if (this->acceptern() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->acceptern(), output);
  }

  // optional string accepterv = 2;
  if (this->accepterv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accepterv().data(), this->accepterv().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "simplepaxos.Accept.accepterv");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->accepterv(), output);
  }

  // @@protoc_insertion_point(serialize_end:simplepaxos.Accept)
}

::google::protobuf::uint8* Accept::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:simplepaxos.Accept)
  // optional uint64 acceptern = 1;
  if (this->acceptern() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->acceptern(), target);
  }

  // optional string accepterv = 2;
  if (this->accepterv().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accepterv().data(), this->accepterv().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "simplepaxos.Accept.accepterv");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->accepterv(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:simplepaxos.Accept)
  return target;
}

int Accept::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:simplepaxos.Accept)
  int total_size = 0;

  // optional uint64 acceptern = 1;
  if (this->acceptern() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->acceptern());
  }

  // optional string accepterv = 2;
  if (this->accepterv().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->accepterv());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Accept::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:simplepaxos.Accept)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Accept* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Accept>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:simplepaxos.Accept)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:simplepaxos.Accept)
    MergeFrom(*source);
  }
}

void Accept::MergeFrom(const Accept& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:simplepaxos.Accept)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.acceptern() != 0) {
    set_acceptern(from.acceptern());
  }
  if (from.accepterv().size() > 0) {

    accepterv_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accepterv_);
  }
}

void Accept::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:simplepaxos.Accept)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Accept::CopyFrom(const Accept& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:simplepaxos.Accept)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Accept::IsInitialized() const {

  return true;
}

void Accept::Swap(Accept* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Accept::InternalSwap(Accept* other) {
  std::swap(acceptern_, other->acceptern_);
  accepterv_.Swap(&other->accepterv_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Accept::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Accept_descriptor_;
  metadata.reflection = Accept_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Accept

// optional uint64 acceptern = 1;
void Accept::clear_acceptern() {
  acceptern_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 Accept::acceptern() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Accept.acceptern)
  return acceptern_;
}
 void Accept::set_acceptern(::google::protobuf::uint64 value) {
  
  acceptern_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Accept.acceptern)
}

// optional string accepterv = 2;
void Accept::clear_accepterv() {
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Accept::accepterv() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Accept.accepterv)
  return accepterv_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Accept::set_accepterv(const ::std::string& value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:simplepaxos.Accept.accepterv)
}
 void Accept::set_accepterv(const char* value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:simplepaxos.Accept.accepterv)
}
 void Accept::set_accepterv(const char* value, size_t size) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:simplepaxos.Accept.accepterv)
}
 ::std::string* Accept::mutable_accepterv() {
  
  // @@protoc_insertion_point(field_mutable:simplepaxos.Accept.accepterv)
  return accepterv_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Accept::release_accepterv() {
  // @@protoc_insertion_point(field_release:simplepaxos.Accept.accepterv)
  
  return accepterv_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Accept::set_allocated_accepterv(::std::string* accepterv) {
  if (accepterv != NULL) {
    
  } else {
    
  }
  accepterv_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accepterv);
  // @@protoc_insertion_point(field_set_allocated:simplepaxos.Accept.accepterv)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace simplepaxos

// @@protoc_insertion_point(global_scope)
