// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_paxos.proto

#ifndef PROTOBUF_simple_5fpaxos_2eproto__INCLUDED
#define PROTOBUF_simple_5fpaxos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace simplepaxos {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_simple_5fpaxos_2eproto();
void protobuf_AssignDesc_simple_5fpaxos_2eproto();
void protobuf_ShutdownFile_simple_5fpaxos_2eproto();

class Accept;
class AcceptRet;
class Prepare;
class PrepareRet;

// ===================================================================

class PrepareRet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:simplepaxos.PrepareRet) */ {
 public:
  PrepareRet();
  virtual ~PrepareRet();

  PrepareRet(const PrepareRet& from);

  inline PrepareRet& operator=(const PrepareRet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrepareRet& default_instance();

  void Swap(PrepareRet* other);

  // implements Message ----------------------------------------------

  inline PrepareRet* New() const { return New(NULL); }

  PrepareRet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrepareRet& from);
  void MergeFrom(const PrepareRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrepareRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 instanceid = 1;
  void clear_instanceid();
  static const int kInstanceidFieldNumber = 1;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // optional uint64 proposaln = 2;
  void clear_proposaln();
  static const int kProposalnFieldNumber = 2;
  ::google::protobuf::uint64 proposaln() const;
  void set_proposaln(::google::protobuf::uint64 value);

  // optional uint64 acceptern = 3;
  void clear_acceptern();
  static const int kAccepternFieldNumber = 3;
  ::google::protobuf::uint64 acceptern() const;
  void set_acceptern(::google::protobuf::uint64 value);

  // optional string accepterv = 4;
  void clear_accepterv();
  static const int kAcceptervFieldNumber = 4;
  const ::std::string& accepterv() const;
  void set_accepterv(const ::std::string& value);
  void set_accepterv(const char* value);
  void set_accepterv(const char* value, size_t size);
  ::std::string* mutable_accepterv();
  ::std::string* release_accepterv();
  void set_allocated_accepterv(::std::string* accepterv);

  // optional bool isok = 5;
  void clear_isok();
  static const int kIsokFieldNumber = 5;
  bool isok() const;
  void set_isok(bool value);

  // @@protoc_insertion_point(class_scope:simplepaxos.PrepareRet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 proposaln_;
  ::google::protobuf::uint64 acceptern_;
  ::google::protobuf::internal::ArenaStringPtr accepterv_;
  bool isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_simple_5fpaxos_2eproto();
  friend void protobuf_AssignDesc_simple_5fpaxos_2eproto();
  friend void protobuf_ShutdownFile_simple_5fpaxos_2eproto();

  void InitAsDefaultInstance();
  static PrepareRet* default_instance_;
};
// -------------------------------------------------------------------

class AcceptRet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:simplepaxos.AcceptRet) */ {
 public:
  AcceptRet();
  virtual ~AcceptRet();

  AcceptRet(const AcceptRet& from);

  inline AcceptRet& operator=(const AcceptRet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AcceptRet& default_instance();

  void Swap(AcceptRet* other);

  // implements Message ----------------------------------------------

  inline AcceptRet* New() const { return New(NULL); }

  AcceptRet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AcceptRet& from);
  void MergeFrom(const AcceptRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AcceptRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 instanceid = 1;
  void clear_instanceid();
  static const int kInstanceidFieldNumber = 1;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // optional uint64 proposaln = 2;
  void clear_proposaln();
  static const int kProposalnFieldNumber = 2;
  ::google::protobuf::uint64 proposaln() const;
  void set_proposaln(::google::protobuf::uint64 value);

  // optional bool isok = 3;
  void clear_isok();
  static const int kIsokFieldNumber = 3;
  bool isok() const;
  void set_isok(bool value);

  // @@protoc_insertion_point(class_scope:simplepaxos.AcceptRet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 proposaln_;
  bool isok_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_simple_5fpaxos_2eproto();
  friend void protobuf_AssignDesc_simple_5fpaxos_2eproto();
  friend void protobuf_ShutdownFile_simple_5fpaxos_2eproto();

  void InitAsDefaultInstance();
  static AcceptRet* default_instance_;
};
// -------------------------------------------------------------------

class Prepare : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:simplepaxos.Prepare) */ {
 public:
  Prepare();
  virtual ~Prepare();

  Prepare(const Prepare& from);

  inline Prepare& operator=(const Prepare& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Prepare& default_instance();

  void Swap(Prepare* other);

  // implements Message ----------------------------------------------

  inline Prepare* New() const { return New(NULL); }

  Prepare* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Prepare& from);
  void MergeFrom(const Prepare& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Prepare* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 instanceid = 1;
  void clear_instanceid();
  static const int kInstanceidFieldNumber = 1;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // optional uint64 proposaln = 2;
  void clear_proposaln();
  static const int kProposalnFieldNumber = 2;
  ::google::protobuf::uint64 proposaln() const;
  void set_proposaln(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:simplepaxos.Prepare)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 proposaln_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_simple_5fpaxos_2eproto();
  friend void protobuf_AssignDesc_simple_5fpaxos_2eproto();
  friend void protobuf_ShutdownFile_simple_5fpaxos_2eproto();

  void InitAsDefaultInstance();
  static Prepare* default_instance_;
};
// -------------------------------------------------------------------

class Accept : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:simplepaxos.Accept) */ {
 public:
  Accept();
  virtual ~Accept();

  Accept(const Accept& from);

  inline Accept& operator=(const Accept& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Accept& default_instance();

  void Swap(Accept* other);

  // implements Message ----------------------------------------------

  inline Accept* New() const { return New(NULL); }

  Accept* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Accept& from);
  void MergeFrom(const Accept& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Accept* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 instanceid = 1;
  void clear_instanceid();
  static const int kInstanceidFieldNumber = 1;
  ::google::protobuf::uint64 instanceid() const;
  void set_instanceid(::google::protobuf::uint64 value);

  // optional uint64 acceptern = 2;
  void clear_acceptern();
  static const int kAccepternFieldNumber = 2;
  ::google::protobuf::uint64 acceptern() const;
  void set_acceptern(::google::protobuf::uint64 value);

  // optional string accepterv = 3;
  void clear_accepterv();
  static const int kAcceptervFieldNumber = 3;
  const ::std::string& accepterv() const;
  void set_accepterv(const ::std::string& value);
  void set_accepterv(const char* value);
  void set_accepterv(const char* value, size_t size);
  ::std::string* mutable_accepterv();
  ::std::string* release_accepterv();
  void set_allocated_accepterv(::std::string* accepterv);

  // @@protoc_insertion_point(class_scope:simplepaxos.Accept)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 instanceid_;
  ::google::protobuf::uint64 acceptern_;
  ::google::protobuf::internal::ArenaStringPtr accepterv_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_simple_5fpaxos_2eproto();
  friend void protobuf_AssignDesc_simple_5fpaxos_2eproto();
  friend void protobuf_ShutdownFile_simple_5fpaxos_2eproto();

  void InitAsDefaultInstance();
  static Accept* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PrepareRet

// optional uint64 instanceid = 1;
inline void PrepareRet::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PrepareRet::instanceid() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.instanceid)
  return instanceid_;
}
inline void PrepareRet::set_instanceid(::google::protobuf::uint64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.instanceid)
}

// optional uint64 proposaln = 2;
inline void PrepareRet::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PrepareRet::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.proposaln)
  return proposaln_;
}
inline void PrepareRet::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.proposaln)
}

// optional uint64 acceptern = 3;
inline void PrepareRet::clear_acceptern() {
  acceptern_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PrepareRet::acceptern() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.acceptern)
  return acceptern_;
}
inline void PrepareRet::set_acceptern(::google::protobuf::uint64 value) {
  
  acceptern_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.acceptern)
}

// optional string accepterv = 4;
inline void PrepareRet::clear_accepterv() {
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PrepareRet::accepterv() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.accepterv)
  return accepterv_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PrepareRet::set_accepterv(const ::std::string& value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.accepterv)
}
inline void PrepareRet::set_accepterv(const char* value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:simplepaxos.PrepareRet.accepterv)
}
inline void PrepareRet::set_accepterv(const char* value, size_t size) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:simplepaxos.PrepareRet.accepterv)
}
inline ::std::string* PrepareRet::mutable_accepterv() {
  
  // @@protoc_insertion_point(field_mutable:simplepaxos.PrepareRet.accepterv)
  return accepterv_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PrepareRet::release_accepterv() {
  // @@protoc_insertion_point(field_release:simplepaxos.PrepareRet.accepterv)
  
  return accepterv_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PrepareRet::set_allocated_accepterv(::std::string* accepterv) {
  if (accepterv != NULL) {
    
  } else {
    
  }
  accepterv_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accepterv);
  // @@protoc_insertion_point(field_set_allocated:simplepaxos.PrepareRet.accepterv)
}

// optional bool isok = 5;
inline void PrepareRet::clear_isok() {
  isok_ = false;
}
inline bool PrepareRet::isok() const {
  // @@protoc_insertion_point(field_get:simplepaxos.PrepareRet.isok)
  return isok_;
}
inline void PrepareRet::set_isok(bool value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.PrepareRet.isok)
}

// -------------------------------------------------------------------

// AcceptRet

// optional uint64 instanceid = 1;
inline void AcceptRet::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AcceptRet::instanceid() const {
  // @@protoc_insertion_point(field_get:simplepaxos.AcceptRet.instanceid)
  return instanceid_;
}
inline void AcceptRet::set_instanceid(::google::protobuf::uint64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.AcceptRet.instanceid)
}

// optional uint64 proposaln = 2;
inline void AcceptRet::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AcceptRet::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.AcceptRet.proposaln)
  return proposaln_;
}
inline void AcceptRet::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.AcceptRet.proposaln)
}

// optional bool isok = 3;
inline void AcceptRet::clear_isok() {
  isok_ = false;
}
inline bool AcceptRet::isok() const {
  // @@protoc_insertion_point(field_get:simplepaxos.AcceptRet.isok)
  return isok_;
}
inline void AcceptRet::set_isok(bool value) {
  
  isok_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.AcceptRet.isok)
}

// -------------------------------------------------------------------

// Prepare

// optional uint64 instanceid = 1;
inline void Prepare::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Prepare::instanceid() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Prepare.instanceid)
  return instanceid_;
}
inline void Prepare::set_instanceid(::google::protobuf::uint64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Prepare.instanceid)
}

// optional uint64 proposaln = 2;
inline void Prepare::clear_proposaln() {
  proposaln_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Prepare::proposaln() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Prepare.proposaln)
  return proposaln_;
}
inline void Prepare::set_proposaln(::google::protobuf::uint64 value) {
  
  proposaln_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Prepare.proposaln)
}

// -------------------------------------------------------------------

// Accept

// optional uint64 instanceid = 1;
inline void Accept::clear_instanceid() {
  instanceid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Accept::instanceid() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Accept.instanceid)
  return instanceid_;
}
inline void Accept::set_instanceid(::google::protobuf::uint64 value) {
  
  instanceid_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Accept.instanceid)
}

// optional uint64 acceptern = 2;
inline void Accept::clear_acceptern() {
  acceptern_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Accept::acceptern() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Accept.acceptern)
  return acceptern_;
}
inline void Accept::set_acceptern(::google::protobuf::uint64 value) {
  
  acceptern_ = value;
  // @@protoc_insertion_point(field_set:simplepaxos.Accept.acceptern)
}

// optional string accepterv = 3;
inline void Accept::clear_accepterv() {
  accepterv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Accept::accepterv() const {
  // @@protoc_insertion_point(field_get:simplepaxos.Accept.accepterv)
  return accepterv_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Accept::set_accepterv(const ::std::string& value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:simplepaxos.Accept.accepterv)
}
inline void Accept::set_accepterv(const char* value) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:simplepaxos.Accept.accepterv)
}
inline void Accept::set_accepterv(const char* value, size_t size) {
  
  accepterv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:simplepaxos.Accept.accepterv)
}
inline ::std::string* Accept::mutable_accepterv() {
  
  // @@protoc_insertion_point(field_mutable:simplepaxos.Accept.accepterv)
  return accepterv_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Accept::release_accepterv() {
  // @@protoc_insertion_point(field_release:simplepaxos.Accept.accepterv)
  
  return accepterv_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Accept::set_allocated_accepterv(::std::string* accepterv) {
  if (accepterv != NULL) {
    
  } else {
    
  }
  accepterv_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accepterv);
  // @@protoc_insertion_point(field_set_allocated:simplepaxos.Accept.accepterv)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace simplepaxos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_simple_5fpaxos_2eproto__INCLUDED
